### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chraibi** [pozapas/awesome-crowdynamics#2]
Since all software are open-source I suggest to add the specific name of the license to the last column instead of "open-source.

**Comment by pozapas** [comment]
@chraibi What do you think about replacing the license with a programming language?

**Comment by chraibi** [comment]
Maybe even better!

**Comment by chraibi** [comment]
@pozapas Can you create a PR for this?

**Comment by pozapas** [comment]
@chraibi I have created a PR. Please review it.
